services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn catalog.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: catalog.settings
      - key: PYTHON_VERSION
        value: 3.11
